# Generated by Django 5.0.6 on 2024-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('waitingapproval', 'waitingapproval'), ('active', 'active'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
    ]
